### PR TITLE
Added purple color to navbar

### PR DESCRIPTION
**Pull request by sid172014**

### CODE REVIEW

**Comment by thecuriousteam** [comment]
@sid172014, your latest change is not yet visible please push the changes and don't forget to take the latest pull

Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues

**Comment by sid172014** [comment]
Hey @thecuriousteam im so sorry for that i had made the changes one another branch, i hope the current commit fixes the navbar color issue and this is how the website looks now ... 

Screenshot 2023-10-20 at 5 55 00 PM

Please let me know if there's anything else i can help with ..

**Comment by thecuriousteam** [comment]
Please can you use the color code #9004fc .

**Comment by sid172014** [comment]
Hey @thecuriousteam i've adjusted the navbar color code according to your instructions , please have a look into the latest commit. Looking forward for further instructions ...

**Comment by thecuriousteam** [comment]
@sid172014 are you part of curious onboarding team?

**Comment by sid172014** [comment]
Yes @thecuriousteam

**Pull request merged**
