### PR TITLE
Added sticky navbar 

### PR DESCRIPTION
**Pull request by nerdyawedee**

### CODE REVIEW

**Comment by nerdyawedee** [comment]
Added hover effect

**Comment by thecuriousteam** [comment]
please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by nerdyawedee** [comment]
i have use react to the navbar ?

**Comment by OmPanpatil** [comment]
can i work on it. the sticky navbar will enhance the website. please let me know

**Comment by thecuriousteam** [comment]
@OmPanpatil and @nerdyawedee please take the latest pull, **read the instructions** and you can work,

Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please write the comments in your source code for development work and don't forget to attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues

Thanks & Regards
The Curious Team

**Pull request closed without merging**
