### PR TITLE
Redesign AllApps.jsx , add more functionality

### PR DESCRIPTION
**Pull request by samrat2k03**
i moved vanila into reactjs , improved navbar and other components ....

### CODE REVIEW

**Comment by samrat2k03** [comment]
screenshots:
Screenshot (117) 
Screenshot (112)
Screenshot (113)
Screenshot (114)
Screenshot (115)
Screenshot (116)

**Comment by thecuriousteam** [comment]
please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by samrat2k03** [comment]
I rephrased the issue into 'Refactor the project with React.js for Improved Performance and Modern UI Styling'.
Could you kindly provide some feedback about pull ....

**Comment by samrat2k03** [comment]
changes done:
- redesigned ```AllApps.jsx``` and added many thibg like list from the `constant.js` file and if user click the list , it will automatically route the corresponding route/page
- add link in `sidebar` title `PyLibLog` when user clicks it routes to '/' 

screenshot : what i do in project:
Screenshot (118)

**Comment by samrat2k03** [comment]
i've rephrased the pull request ```Project moved to the reactjs , imporved performance & ui styling``` into ```Redesign AllApps.jsx , add more functionality```  issue: #108

**Pull request closed without merging**
