### PR TITLE
I have added a loading progress bar

### PR DESCRIPTION
**Pull request by VishnuAmit**
When you navigate to some other page by clicking the buttons, the loading bar shows up adding a good user experience to the webpage. Modified the existing JavaScript function and put that into a separate file named logic.js.

Also, some changes in the ref tag link :)

### CODE REVIEW

**Comment by thecuriousteam** [comment]
please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by VishnuAmit** [comment]
> please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join
> 
> Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by VishnuAmit** [comment]
Hey @thecuriousteam. Kindly merge my pull request :)

**Comment by thecuriousteam** [comment]
please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by thecuriousteam** [comment]
@VishnuAmit your code is giving merge conflicts

Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please write the comments in your source code for development work and don't forget to attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues

Thanks & Regards
The Curious Team

**Comment by VishnuAmit** [comment]
Yea ok. I am working on it 👍

**Pull request closed without merging**
