### PR TITLE
Logo for PyLigLog

### PR DESCRIPTION
**Pull request by ayaan-qadri**
I tried to create logo for PyLibLog as per issue #213

### CODE REVIEW

**Comment by thecuriousteam** [comment]
Please attach the screenshots @PentW0lf

**Comment by thecuriousteam** [comment]
Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues

Thanks & Regards
The Curious Team

**Comment by PentW0lf** [comment]
pyliblog

**Comment by thecuriousteam** [comment]
Can we have some more unique?

**Comment by PentW0lf** [comment]
The logo is representing: book logo - represent Library encyclopedia, python logo - represent python (left side of book),  right side of book - represent codes.

**Comment by PentW0lf** [comment]
> Can we have some more unique?

What should be unique? text or logo or everything?

**Pull request closed without merging**
