### PR TITLE
Sidebar Made Responsive

### PR DESCRIPTION
**Pull request by manan18**

### CODE REVIEW

**Comment by ayush-agarwal-190** [comment]
Actually we want to extend it , Like if you see , Article Introduction to  Python the  side bar is over , we need to extend it.
image

**Comment by thecuriousteam** [comment]
@manan18 there is issue in the code

**Comment by manan18** [comment]
I've made some changes to the pull request and added a new commit, please have a look. pr #147

**Comment by ayush-agarwal-190** [comment]
image
It still showing the error.

**Comment by manan18** [comment]
jotai is an independent library which you will have to install either using yarn or npm.
it is usually used for managing global states.
type:
**yarn add jotai**
on the terminal and it will install jotai on your system/server

**Pull request closed without merging**
