### PR TITLE
Dropdown has been removed

### PR DESCRIPTION
**Pull request by Amit-Vikram-Singh-07**
Fixes: #69

### CODE REVIEW

**Comment by PlanetKumbhaj** [comment]
@Amit-Vikram-Singh-07 You need to again push the repo to your fork repo.

**Comment by Amit-Vikram-Singh-07** [comment]
I guess , now my forked repo is synced to the base repo

**Comment by thecuriousteam** [comment]
please rephrase the issue by considering the react js technology and if you didn't joined onboarding group please do join

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link [Curious Developers Community - Hacktoberfest](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)

**Comment by Amit-Vikram-Singh-07** [comment]
@thecuriousteam  Please review my #69 PR

**Pull request closed without merging**
